services:
  api:
    image: back:latest
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network
    depends_on:
      - db
  web:
    image: front:latest
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: offices_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./backend/DbDump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4:snapshot
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    networks:
      - app-network

volumes:
  pg-data:
  
networks:
  app-network:
    driver: bridge
